CREATE TABLE [dbo].[DwAsset] (
    [AssetNumber]                NVARCHAR (450)  NOT NULL,
    [ParentAssetNumber]          NVARCHAR (MAX)  NULL,
    [PropertyNumber]             NVARCHAR (MAX)  NULL,
    [PropertyName]               NVARCHAR (MAX)  NULL,
    [CompanyId]                  NVARCHAR (MAX)  NULL,
    [ElectoralRiding]            NVARCHAR (MAX)  NULL,
    [CFAChargeType]              NVARCHAR (MAX)  NULL,
    [FacilityManagementZone]     NVARCHAR (MAX)  NULL,
    [Address]                    NVARCHAR (MAX)  NULL,
    [City]                       NVARCHAR (MAX)  NULL,
    [Municipality]               NVARCHAR (MAX)  NULL,
    [County]                     NVARCHAR (MAX)  NULL,
    [PostalCode]                 NVARCHAR (MAX)  NULL,
    [Region]                     NVARCHAR (MAX)  NULL,
    [Active]                     BIT             NOT NULL,
    [Status]                     NVARCHAR (MAX)  NULL,
    [AssetUse]                   NVARCHAR (MAX)  NULL,
    [AssetCategory]              NVARCHAR (MAX)  NULL,
    [Tier]                       NVARCHAR (MAX)  NULL,
    [GrossArea]                  DECIMAL (18, 2) NOT NULL,
    [AreaMeasureUnit]            NVARCHAR (MAX)  NULL,
    [HeritageStatus]             NVARCHAR (MAX)  NULL,
    [OwnershipType]              NVARCHAR (MAX)  NULL,
    [ServiceProvider]            NVARCHAR (MAX)  NULL,
    [ServiceProviderManager]     NVARCHAR (MAX)  NULL,
    [ServiceProviderEmail]       NVARCHAR (MAX)  NULL,
    [ServiceProviderPhoneNumber] NVARCHAR (MAX)  NULL,
    [OMResponsibility]           NVARCHAR (MAX)  NULL,
    [RentableArea]               DECIMAL (18, 2) NOT NULL,
    [FacilityManager]            NVARCHAR (MAX)  NULL,
    [Floors]                     INT             NOT NULL,
    [ConstructionYear]           INT             NOT NULL,
    [PropertyUse]                NVARCHAR (MAX)  NULL,
    [ModifiedDate]               DATETIME2 (7)   NOT NULL,
    CONSTRAINT [PK_DwAsset] PRIMARY KEY CLUSTERED ([AssetNumber] ASC)
);

