CREATE TABLE [dbo].[ioiAsset] (
    [AssetNumber]                 VARCHAR (255)  NOT NULL,
    [AssetName]                   VARCHAR (255)  NULL,
    [ParentAssetNumber]           VARCHAR (255)  NULL,
    [PropertyNumber]              VARCHAR (255)  NULL,
    [PropertyName]                VARCHAR (255)  NULL,
    [CompanyID]                   VARCHAR (255)  NULL,
    [ElectoralRiding]             VARCHAR (255)  NULL,
    [CFAChargeType]               VARCHAR (255)  NULL,
    [FacilityManagementZone]      VARCHAR (255)  NULL,
    [Address]                     VARCHAR (255)  NULL,
    [City]                        VARCHAR (255)  NULL,
    [Municipality]                VARCHAR (255)  NULL,
    [County]                      VARCHAR (255)  NULL,
    [PostalCode]                  VARCHAR (255)  NULL,
    [Region]                      VARCHAR (255)  NULL,
    [Active]                      BIT            NULL,
    [Status]                      VARCHAR (255)  NULL,
    [AssetUse]                    VARCHAR (255)  NULL,
    [AssetCategory]               VARCHAR (255)  NULL,
    [Tier]                        VARCHAR (255)  NULL,
    [GrossArea]                   DECIMAL (9, 2) NULL,
    [AreaMeasureUnit]             VARCHAR (255)  NULL,
    [HeritageStatus]              VARCHAR (255)  NULL,
    [OwnershipType]               VARCHAR (255)  NULL,
    [ServiceProvider]             VARCHAR (255)  NULL,
    [ServiceProviderManager]      VARCHAR (255)  NULL,
    [ServiceProviderEmail]        VARCHAR (255)  NULL,
    [ServiceProviderPhoneNumber]  VARCHAR (255)  NULL,
    [OMResponsibility]            VARCHAR (255)  NULL,
    [CapitalRepairResponsibility] VARCHAR (255)  NULL,
    [RentableArea]                DECIMAL (9, 2) NULL,
    [FacilityManager]             VARCHAR (255)  NULL,
    [Floors]                      INT            NULL,
    [ConstructionYear]            VARCHAR (255)  NULL,
    [PropertyUse]                 VARCHAR (255)  NULL,
    [ModifiedDate]                VARCHAR (255)  NULL
);

