CREATE TABLE [dbo].[RequestData] (
    [LastModified]                         DATETIME2 (7)   NULL,
    [ModifiedBy]                           INT             NULL,
    [Deleted]                              BIT             NOT NULL,
    [RequestDataId]                        INT             IDENTITY (1, 1) NOT NULL,
    [Form1Id]                              NVARCHAR (MAX)  NULL,
    [RequestTypeId]                        INT             NOT NULL,
    [WorkflowInstanceId]                   INT             NOT NULL,
    [SubcategoryId]                        INT             NULL,
    [RateChangeTypeId]                     INT             NULL,
    [AmendTypeId]                          INT             NULL,
    [AmendedRequestId]                     INT             NULL,
    [GLease]                               NVARCHAR (50)   NULL,
    [LLease]                               NVARCHAR (50)   NULL,
    [VLease]                               NVARCHAR (50)   NULL,
    [ClientId]                             INT             NULL,
    [InitiatorId]                          INT             NULL,
    [initiatorTitle]                       NVARCHAR (200)  NULL,
    [ReviewerId]                           INT             NULL,
    [ReviewerTitle]                        NVARCHAR (200)  NULL,
    [ClientApprover1Id]                    INT             NULL,
    [ClientApprover1Title]                 NVARCHAR (200)  NULL,
    [ClientApprover2Id]                    INT             NULL,
    [ClientApprover2Title]                 NVARCHAR (200)  NULL,
    [ClientApprover3Id]                    INT             NULL,
    [ClientApprover3Title]                 NVARCHAR (200)  NULL,
    [IoClientVpApproverId]                 INT             NULL,
    [IoClientVpApproverTitle]              NVARCHAR (200)  NULL,
    [PremApproverId]                       INT             NULL,
    [PremApproverTitle]                    NVARCHAR (200)  NULL,
    [RealtyOperationDirectorApproverId]    INT             NULL,
    [RealtyOperationDirectorApproverTitle] NVARCHAR (200)  NULL,
    [ProgramName]                          NVARCHAR (200)  NULL,
    [PropertyNumber]                       NVARCHAR (200)  NULL,
    [LandBuildingNumber]                   NVARCHAR (200)  NULL,
    [Address]                              NVARCHAR (200)  NULL,
    [City]                                 NVARCHAR (200)  NULL,
    [Region]                               NVARCHAR (200)  NULL,
    [Floor]                                NVARCHAR (200)  NULL,
    [Unit]                                 NVARCHAR (200)  NULL,
    [Suite]                                NVARCHAR (200)  NULL,
    [OffsettingForm1Id]                    NVARCHAR (200)  NULL,
    [RationaleId]                          INT             NULL,
    [RationaleComment]                     NVARCHAR (200)  NULL,
    [SpaceTypeCategoryId]                  INT             NULL,
    [RequestedRsf]                         DECIMAL (18, 2) NULL,
    [CurrentRsf]                           DECIMAL (18, 2) NULL,
    [RSF]                                  DECIMAL (18, 2) NULL,
    [RemeasuredRsf]                        DECIMAL (18, 2) NULL,
    [DeltaRsf]                             DECIMAL (18, 2) NULL,
    [ApproximateRsf]                       DECIMAL (18, 2) NULL,
    [NumberOfStaff]                        INT             NULL,
    [RsfPerStaff]                          DECIMAL (18, 2) NULL,
    [SpaceChange]                          NVARCHAR (200)  NULL,
    [NoticeDate]                           NVARCHAR (200)  NULL,
    [TermStartDate]                        NVARCHAR (200)  NULL,
    [TermEndDate]                          NVARCHAR (200)  NULL,
    [ClientVacateDate]                     NVARCHAR (200)  NULL,
    [CurrentTermEndDate]                   NVARCHAR (200)  NULL,
    [RevisedTermEndDate]                   NVARCHAR (200)  NULL,
    [TransferDate]                         NVARCHAR (200)  NULL,
    [EffectiveDate]                        NVARCHAR (200)  NULL,
    [PlannedOccupancyDate]                 NVARCHAR (200)  NULL,
    [NewTermStartDate]                     NVARCHAR (200)  NULL,
    [NewTermEndDate]                       NVARCHAR (200)  NULL,
    [newTermDurationInMonths]              INT             NULL,
    [IsOaNo1]                              NVARCHAR (10)   NULL,
    [SvpApprovalNameAndDate]               NVARCHAR (200)  NULL,
    [BomaStandardFromId]                   INT             NULL,
    [BomaStandardToId]                     INT             NULL,
    [MinistryHoldOfVacantSpaceId]          INT             NULL,
    [DateOfCaoApproval]                    NVARCHAR (200)  NULL,
    [EstimatedBaseRentRate]                DECIMAL (18, 2) NULL,
    [EstimatedOmRate]                      DECIMAL (18, 2) NULL,
    [EstimatedTaxRate]                     DECIMAL (18, 2) NULL,
    [EstimatedManagementRate]              DECIMAL (18, 2) NULL,
    [GrossRent]                            DECIMAL (20, 2) NULL,
    [TotalGrossRent]                       DECIMAL (20, 2) NULL,
    [OffsetRequestorId]                    INT             NULL,
    [RequestorId]                          INT             NULL,
    [IoVpApproverId]                       INT             NULL,
    [ClientDirection]                      NVARCHAR (2500) NULL,
    [ConstructionRate]                     DECIMAL (18, 2) NULL,
    [Fees]                                 DECIMAL (18, 2) NULL,
    [Others]                               DECIMAL (18, 2) NULL,
    [PlanningDesignRate]                   DECIMAL (18, 2) NULL,
    [ReviewApprovalDate]                   DATETIME2 (7)   NULL,
    [IoClientVpApprovalDate]               DATETIME2 (7)   NULL,
    [PremApprovalDate]                     DATETIME2 (7)   NULL,
    [RealtyOperationDirectorApprovalDate]  DATETIME2 (7)   NULL,
    [Client1ApprovalDate]                  DATETIME2 (7)   NULL,
    [Client2ApprovalDate]                  DATETIME2 (7)   NULL,
    [Client3ApprovalDate]                  DATETIME2 (7)   NULL,
    [ClientApprovalCompletionDate]         DATETIME2 (7)   NULL,
    [ClientAcknowledgesRecommendation]     INT             NULL,
    [ClientAcknowledgesDetails]            NVARCHAR (MAX)  NULL,
    [FromLLeaseFromOther]                  INT             NULL,
    [OffsetLLease]                         NVARCHAR (200)  NULL,
    [OffsetRsf]                            DECIMAL (18, 2) NULL,
    [FromOtherComment]                     NVARCHAR (MAX)  NULL,
    [IncreaseDecrease]                     NVARCHAR (10)   NULL,
    [TotalProjectCostsPsf]                 DECIMAL (20, 2) NULL,
    [TotalProjectCosts]                    DECIMAL (20, 2) NULL,
    [NewBaseRentRate]                      DECIMAL (18, 2) NULL,
    [NewOmRate]                            DECIMAL (18, 2) NULL,
    [NewManagementRate]                    DECIMAL (18, 2) NULL,
    [NewTaxRate]                           DECIMAL (18, 2) NULL,
    [NewGrossRent]                         DECIMAL (20, 2) NULL,
    [NewTotalGrossRent]                    DECIMAL (20, 2) NULL,
    [BaseRentRate]                         DECIMAL (18, 2) NULL,
    [OmRate]                               DECIMAL (18, 2) NULL,
    [ManagementRate]                       DECIMAL (18, 2) NULL,
    [TaxRate]                              DECIMAL (18, 2) NULL,
    [RemeasuredBaseRentRate]               DECIMAL (18, 2) NULL,
    [RemeasuredOmRate]                     DECIMAL (18, 2) NULL,
    [RemeasuredManagementRate]             DECIMAL (18, 2) NULL,
    [RemeasuredTaxRate]                    DECIMAL (18, 2) NULL,
    [RemeasuredGrossRent]                  DECIMAL (20, 2) NULL,
    [RemeasuredTotalGrossRent]             DECIMAL (20, 2) NULL,
    [ClientReceivingSpaceId]               INT             NULL,
    [OffsetToGrowthForm1Id]                NVARCHAR (200)  NULL,
    [OffsetToGrowthLLeaseAppliedTo]        NVARCHAR (200)  NULL,
    [OffsetToGrowthRsfAppliedTo]           NVARCHAR (200)  NULL,
    [EstimatedGrossRent]                   DECIMAL (20, 2) NULL,
    [EstimatedTotalGrossRent]              DECIMAL (20, 2) NULL,
    CONSTRAINT [PK_RequestData] PRIMARY KEY CLUSTERED ([RequestDataId] ASC),
    CONSTRAINT [FK_RequestData_AmendType_AmendTypeId] FOREIGN KEY ([AmendTypeId]) REFERENCES [dbo].[AmendType] ([AmendTypeId]),
    CONSTRAINT [FK_RequestData_RequestData_AmendedRequestId] FOREIGN KEY ([AmendedRequestId]) REFERENCES [dbo].[RequestData] ([RequestDataId]),
    CONSTRAINT [FK_RequestData_RequestType_RequestTypeId] FOREIGN KEY ([RequestTypeId]) REFERENCES [dbo].[RequestType] ([RequestTypeId]),
    CONSTRAINT [FK_RequestData_WorkflowInstance_WorkflowInstanceId] FOREIGN KEY ([WorkflowInstanceId]) REFERENCES [dbo].[WorkflowInstance] ([WorkflowInstanceId])
);

