CREATE TABLE [dbo].[RequestOffsetData] (
    [LastModified]                              DATETIME2 (7)   NULL,
    [ModifiedBy]                                INT             NULL,
    [Deleted]                                   BIT             NOT NULL,
    [RequestOffsetDataId]                       INT             IDENTITY (1, 1) NOT NULL,
    [Form1Id]                                   NVARCHAR (MAX)  NULL,
    [RequestDataId]                             INT             NOT NULL,
    [CSM]                                       INT             NULL,
    [VPApprover]                                INT             NULL,
    [MinistryApprover1]                         INT             NULL,
    [MinistryApprover2]                         INT             NULL,
    [MinistryApprover3]                         INT             NULL,
    [RequestTypeId]                             INT             NULL,
    [WorkflowInstanceId]                        INT             NULL,
    [SubcategoryId]                             INT             NULL,
    [RateChangeTypeId]                          INT             NULL,
    [GLease]                                    NVARCHAR (50)   NULL,
    [LLease]                                    NVARCHAR (50)   NULL,
    [VLease]                                    NVARCHAR (50)   NULL,
    [ClientId]                                  INT             NULL,
    [InitiatorId]                               INT             NULL,
    [initiatorTitle]                            NVARCHAR (200)  NULL,
    [ReviewerId]                                INT             NULL,
    [ReviewerTitle]                             NVARCHAR (200)  NULL,
    [ClientApprover1Id]                         INT             NULL,
    [ClientApprover1Title]                      NVARCHAR (200)  NULL,
    [ClientApprover2Id]                         INT             NULL,
    [ClientApprover2Title]                      NVARCHAR (200)  NULL,
    [ClientApprover3Id]                         INT             NULL,
    [ClientApprover3Title]                      NVARCHAR (200)  NULL,
    [IoClientVpApproverId]                      INT             NULL,
    [IoClientVpApproverTitle]                   NVARCHAR (200)  NULL,
    [PremApproverId]                            INT             NULL,
    [PremApproverTitle]                         NVARCHAR (200)  NULL,
    [RealtyOperationDirectorApproverId]         INT             NULL,
    [RealtyOperationDirectorApproverTitle]      NVARCHAR (200)  NULL,
    [ProgramName]                               NVARCHAR (200)  NULL,
    [PropertyNumber]                            NVARCHAR (200)  NULL,
    [LandBuildingNumber]                        NVARCHAR (200)  NULL,
    [Address]                                   NVARCHAR (200)  NULL,
    [City]                                      NVARCHAR (200)  NULL,
    [Region]                                    NVARCHAR (50)   NULL,
    [SpaceTypeCategoryId]                       INT             NULL,
    [RequestedRsf]                              DECIMAL (18, 2) NULL,
    [RSF]                                       DECIMAL (18, 2) NULL,
    [NumberOfStaff]                             INT             NULL,
    [RsfPerStaff]                               DECIMAL (18, 2) NULL,
    [SpaceChange]                               NVARCHAR (200)  NULL,
    [NoticeDate]                                NVARCHAR (200)  NULL,
    [TermStartDate]                             NVARCHAR (200)  NULL,
    [TermEndDate]                               NVARCHAR (200)  NULL,
    [ClientVacateDate]                          NVARCHAR (200)  NULL,
    [CurrentTermEndDate]                        NVARCHAR (200)  NULL,
    [NewTermStartDate]                          NVARCHAR (200)  NULL,
    [NewTermEndDate]                            NVARCHAR (200)  NULL,
    [newTermDurationInMonths]                   INT             NULL,
    [IsOaNo1]                                   NVARCHAR (10)   NULL,
    [SvpApprovalNameAndDate]                    NVARCHAR (200)  NULL,
    [MinistryHoldOfVacantSpaceId]               INT             NULL,
    [DateOfCaoApproval]                         NVARCHAR (200)  NULL,
    [EstimatedBaseRentRate]                     DECIMAL (18, 2) NULL,
    [EstimatedOmRate]                           DECIMAL (18, 2) NULL,
    [EstimatedTaxRate]                          DECIMAL (18, 2) NULL,
    [EstimatedManagementRate]                   DECIMAL (18, 2) NULL,
    [GrossRent]                                 DECIMAL (20, 2) NULL,
    [TotalGrossRent]                            DECIMAL (20, 2) NULL,
    [ClientDirection]                           NVARCHAR (2500) NULL,
    [ConstructionRate]                          DECIMAL (18, 2) NULL,
    [Fees]                                      DECIMAL (18, 2) NULL,
    [Others]                                    DECIMAL (18, 2) NULL,
    [PlanningDesignRate]                        DECIMAL (18, 2) NULL,
    [OffsetFormSubmissionDate]                  DATETIME2 (7)   NULL,
    [ReviewApprovalOffsetDate]                  DATETIME2 (7)   NULL,
    [IoClientVpApprovalOffsetDate]              DATETIME2 (7)   NULL,
    [PremApprovalOffsetDate]                    DATETIME2 (7)   NULL,
    [RealtyOperationDirectorApprovalOffsetDate] DATETIME2 (7)   NULL,
    [Client1ApprovalOffsetDate]                 DATETIME2 (7)   NULL,
    [Client2ApprovalOffsetDate]                 DATETIME2 (7)   NULL,
    [Client3ApprovalOffsetDate]                 DATETIME2 (7)   NULL,
    [ClientApprovalOffsetCompletionDate]        DATETIME2 (7)   NULL,
    [ClientAcknowledgesRecommendation]          INT             NULL,
    [ClientAcknowledgesDetails]                 NVARCHAR (MAX)  NULL,
    [FromLLeaseFromOther]                       INT             NULL,
    [OffsetLLease]                              NVARCHAR (200)  NULL,
    [OffsetRsf]                                 DECIMAL (18, 2) NULL,
    [FromOtherComment]                          NVARCHAR (MAX)  NULL,
    [IncreaseDecrease]                          NVARCHAR (10)   NULL,
    [TotalProjectCostsPsf]                      DECIMAL (20, 2) NULL,
    [TotalProjectCosts]                         DECIMAL (20, 2) NULL,
    [BaseRentRate]                              DECIMAL (18, 2) NULL,
    [OmRate]                                    DECIMAL (18, 2) NULL,
    [ManagementRate]                            DECIMAL (18, 2) NULL,
    [TaxRate]                                   DECIMAL (18, 2) NULL,
    [ClientReceivingSpaceId]                    INT             NULL,
    [EstimatedGrossRent]                        DECIMAL (20, 2) NULL,
    [EstimatedTotalGrossRent]                   DECIMAL (20, 2) NULL,
    [RemeasuredGrossRent]                       DECIMAL (20, 2) NULL,
    [RemeasuredTotalGrossRent]                  DECIMAL (20, 2) NULL,
    [NewGrossRent]                              DECIMAL (20, 2) NULL,
    [NewTotalGrossRent]                         DECIMAL (20, 2) NULL,
    CONSTRAINT [PK_RequestOffsetData] PRIMARY KEY CLUSTERED ([RequestOffsetDataId] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_RequestOffsetData_RequestDataId]
    ON [dbo].[RequestOffsetData]([RequestDataId] ASC);

